import type { ScanResult } from '../scanner/detect'

interface PromptContext {
  url: string
  result: ScanResult
}

export function generatePrompt(ctx: PromptContext): {
  prompt: string
  shortPrompt: string
  manualSteps: string[]
} {
  const { url, result } = ctx

  // Framework-specific versions
  const fixVersions = getFixVersions(result.framework, result.detectedVersion)

  const prompt = `## Fix React2Shell Vulnerability (CVE-2025-55182)

**Scan Result:** ${url} is VULNERABLE to React2Shell
**Severity:** CRITICAL (CVSS 10.0) - Unauthenticated Remote Code Execution
**Framework:** ${result.framework || 'Unknown'} ${result.detectedVersion ? `v${result.detectedVersion}` : ''}

### Required Updates

Update your package.json dependencies to these minimum versions:

\`\`\`json
{
  "dependencies": {
${fixVersions.map(v => `    "${v.package}": "^${v.minVersion}"`).join(',\n')}
  }
}
\`\`\`

### Instructions

1. Update package.json with the versions above
2. Run \`npm install\` (or yarn/pnpm equivalent)
3. Run \`npm run build\` to verify the app builds successfully
4. Test critical functionality before deploying
5. Deploy the updated application immediately

### If You Encounter Breaking Changes

${result.framework === 'nextjs' ? `
- Check Next.js release notes: https://github.com/vercel/next.js/releases
- The patch versions should be backwards compatible
- If using custom server, ensure middleware is updated
` : `
- Check the framework's changelog for breaking changes
- The patch should be backwards compatible in most cases
`}

### Verification

After updating, you can verify the fix by:
1. Re-scanning this URL at react2shellscan.com
2. Checking your package-lock.json for updated versions
3. Looking for the security advisory acknowledgment in your dependency tree

---
*Generated by React2Shell Scanner on ${new Date().toISOString().split('T')[0]}*
`

  const shortPrompt = `Fix CVE-2025-55182 (React2Shell) in my ${result.framework || 'React'} app. Update: ${
    fixVersions.map(v => `${v.package}@${v.minVersion}+`).join(', ')
  }. Then npm install && npm run build.`

  const manualSteps = [
    `Open package.json in your project root`,
    ...fixVersions.map(v => `Update "${v.package}" to "^${v.minVersion}" or higher`),
    `Run: npm install`,
    `Run: npm run build`,
    `Test your application locally`,
    `Deploy to production immediately`,
    `Re-scan at react2shellscan.com to verify the fix`,
  ]

  return { prompt, shortPrompt, manualSteps }
}

function getFixVersions(framework: string | null, detectedVersion: string | null): Array<{
  package: string
  minVersion: string
}> {
  // Based on official advisories as of Jan 2026
  const versions = [
    { package: 'react', minVersion: '19.1.2' },
    { package: 'react-dom', minVersion: '19.1.2' },
  ]

  if (framework === 'nextjs') {
    // Next.js specific versions
    versions.push(
      { package: 'next', minVersion: '15.2.6' },
    )
  }

  // RSC packages that may be direct dependencies
  versions.push(
    { package: 'react-server-dom-webpack', minVersion: '19.1.2' },
  )

  return versions
}

export function generateRawPromptForIDE(ctx: PromptContext): string {
  const { result } = ctx
  const fixVersions = getFixVersions(result.framework, result.detectedVersion)

  return `My ${result.framework || 'React'} application is vulnerable to CVE-2025-55182 (React2Shell), a critical RCE vulnerability.

Please update my package.json to fix this:
${fixVersions.map(v => `- ${v.package} to version ${v.minVersion} or higher`).join('\n')}

After updating package.json:
1. Run npm install
2. Run npm run build to verify everything compiles
3. Check for any breaking changes and fix if needed

This is a critical security fix - the vulnerability allows unauthenticated remote code execution.`
}
